# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-31 11:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20170829_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='board',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Board'),
            preserve_default=False,
        ),
    ]
