# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-06 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_card_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='cover_img',
            field=models.ImageField(blank=True, null=True, upload_to='contents/board/%Y%m%d'),
        ),
    ]
